name: Xpense CI

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Build Xpense"
        uses: actions/checkout@v2

      - name: "Make gradle executable"
        run: chmod +x ./gradlew

      - name: "Build"
        run: ./gradlew build

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Android lint checker"
        uses: actions/checkout@v2

      - name: "Setup JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "Generate gradle checksums"
        run: |
          find buildSrc -name "*.kt" -type f | sort | xargs shasum > gradle-checksums.txt
          cat gradle-checksums.txt

      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-

      - name: "Make gradle executable"
        run: chmod +x ./gradlew

      - name: "Lint debug"
        run: ./gradlew lint

      - name: "Upload report"
        uses: actions/upload-artifact@v2
        with:
          name: "android-lint-report"
          path: ./**/build/reports/lint-results.xml